# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
    - id: check-ast
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: end-of-file-fixer
    - id: detect-private-key
 - repo: git://github.com/antonbabenko/pre-commit-terraform
   rev: v1.50.0
   hooks:
    - id: terraform_fmt
#   - id: terraform_tfsec # comment out if working in ~/ or tfsec hangs trying search the entire home dir for .tf files
#   - id: terraform_tflint
 - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
   rev: v9.1.0
   hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
 - repo: https://github.com/timothycrosley/isort
   rev: 5.9.3
   hooks:
    - id: isort
# - repo: https://gitlab.com/pycqa/flake8
#   rev: 3.8.4
#   hooks:
#    - id: flake8
#      additional_dependencies: [flake8-isort]
